/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.newrelic.videoagent.swig;

public class Core_WrapperJNI {
  public final static native double OBSERVATION_TIME_get();
  public final static native double HEARTBEAT_COUNT_get();
  public final static native long new_TrackerCore();
  public final static native void delete_TrackerCore(long jarg1);
  public final static native long TrackerCore_state(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_updateAttribute__SWIG_0(long jarg1, TrackerCore jarg1_, String jarg2, long jarg3, String jarg4);
  public final static native void TrackerCore_updateAttribute__SWIG_1(long jarg1, TrackerCore jarg1_, String jarg2, long jarg3);
  public final static native void TrackerCore_reset(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_setup(long jarg1, TrackerCore jarg1_);
  public final static native String TrackerCore_getViewId(long jarg1, TrackerCore jarg1_);
  public final static native int TrackerCore_getNumberOfVideos(long jarg1, TrackerCore jarg1_);
  public final static native String TrackerCore_getCoreVersion(long jarg1, TrackerCore jarg1_);
  public final static native String TrackerCore_getViewSession(long jarg1, TrackerCore jarg1_);
  public final static native int TrackerCore_getNumberOfErrors(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendRequest(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendStart(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendEnd(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendPause(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendResume(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendSeekStart(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendSeekEnd(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendBufferStart(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendBufferEnd(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendHeartbeat(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendRenditionChange(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendError(long jarg1, TrackerCore jarg1_, String jarg2);
  public final static native void TrackerCore_sendPlayerReady(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendDownload(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_sendCustomAction__SWIG_0(long jarg1, TrackerCore jarg1_, String jarg2);
  public final static native void TrackerCore_sendCustomAction__SWIG_1(long jarg1, TrackerCore jarg1_, String jarg2, long jarg3);
  public final static native void TrackerCore_setOptions__SWIG_0(long jarg1, TrackerCore jarg1_, long jarg2);
  public final static native void TrackerCore_setOptions__SWIG_1(long jarg1, TrackerCore jarg1_, long jarg2, String jarg3);
  public final static native void TrackerCore_startTimerEvent(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_abortTimerEvent(long jarg1, TrackerCore jarg1_);
  public final static native void TrackerCore_trackerTimeEvent(long jarg1, TrackerCore jarg1_);
  public final static native boolean TrackerCore_setTimestamp(long jarg1, TrackerCore jarg1_, double jarg2, String jarg3);
  public final static native long new_ContentsTrackerCore();
  public final static native void delete_ContentsTrackerCore(long jarg1);
  public final static native void ContentsTrackerCore_reset(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_setup(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendRequest(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendStart(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendEnd(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendPause(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendResume(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendSeekStart(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendSeekEnd(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendBufferStart(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendBufferEnd(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendHeartbeat(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendRenditionChange(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendError(long jarg1, ContentsTrackerCore jarg1_, String jarg2);
  public final static native void ContentsTrackerCore_sendPlayerReady(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendDownload(long jarg1, ContentsTrackerCore jarg1_);
  public final static native void ContentsTrackerCore_sendCustomAction__SWIG_0(long jarg1, ContentsTrackerCore jarg1_, String jarg2);
  public final static native void ContentsTrackerCore_sendCustomAction__SWIG_1(long jarg1, ContentsTrackerCore jarg1_, String jarg2, long jarg3);
  public final static native boolean ContentsTrackerCore_setTimestamp(long jarg1, ContentsTrackerCore jarg1_, double jarg2, String jarg3);
  public final static native void ContentsTrackerCore_adHappened(long jarg1, ContentsTrackerCore jarg1_, double jarg2);
  public final static native long ContentsTrackerCore_SWIGUpcast(long jarg1);
}
