/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.newrelic.videoagent.jni.swig;

public class AdsTrackerCore extends TrackerCore {
  private transient long swigCPtr;

  protected AdsTrackerCore(long cPtr, boolean cMemoryOwn) {
    super(Core_WrapperJNI.AdsTrackerCore_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdsTrackerCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Core_WrapperJNI.delete_AdsTrackerCore(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AdsTrackerCore(ContentsTrackerCore contentsTracker) {
    this(Core_WrapperJNI.new_AdsTrackerCore__SWIG_0(ContentsTrackerCore.getCPtr(contentsTracker), contentsTracker), true);
  }

  public AdsTrackerCore() {
    this(Core_WrapperJNI.new_AdsTrackerCore__SWIG_1(), true);
  }

  public void reset() {
    Core_WrapperJNI.AdsTrackerCore_reset(swigCPtr, this);
  }

  public void setup() {
    Core_WrapperJNI.AdsTrackerCore_setup(swigCPtr, this);
  }

  public void sendRequest() {
    Core_WrapperJNI.AdsTrackerCore_sendRequest(swigCPtr, this);
  }

  public void sendStart() {
    Core_WrapperJNI.AdsTrackerCore_sendStart(swigCPtr, this);
  }

  public void sendEnd() {
    Core_WrapperJNI.AdsTrackerCore_sendEnd(swigCPtr, this);
  }

  public void sendPause() {
    Core_WrapperJNI.AdsTrackerCore_sendPause(swigCPtr, this);
  }

  public void sendResume() {
    Core_WrapperJNI.AdsTrackerCore_sendResume(swigCPtr, this);
  }

  public void sendSeekStart() {
    Core_WrapperJNI.AdsTrackerCore_sendSeekStart(swigCPtr, this);
  }

  public void sendSeekEnd() {
    Core_WrapperJNI.AdsTrackerCore_sendSeekEnd(swigCPtr, this);
  }

  public void sendBufferStart() {
    Core_WrapperJNI.AdsTrackerCore_sendBufferStart(swigCPtr, this);
  }

  public void sendBufferEnd() {
    Core_WrapperJNI.AdsTrackerCore_sendBufferEnd(swigCPtr, this);
  }

  public void sendHeartbeat() {
    Core_WrapperJNI.AdsTrackerCore_sendHeartbeat(swigCPtr, this);
  }

  public void sendRenditionChange() {
    Core_WrapperJNI.AdsTrackerCore_sendRenditionChange(swigCPtr, this);
  }

  public void sendError(String message) {
    Core_WrapperJNI.AdsTrackerCore_sendError(swigCPtr, this, message);
  }

  public void sendPlayerReady() {
    Core_WrapperJNI.AdsTrackerCore_sendPlayerReady(swigCPtr, this);
  }

  public void sendDownload() {
    Core_WrapperJNI.AdsTrackerCore_sendDownload(swigCPtr, this);
  }

  public void sendCustomAction(String name) {
    Core_WrapperJNI.AdsTrackerCore_sendCustomAction__SWIG_0(swigCPtr, this, name);
  }

  public void sendCustomAction(String name, SWIGTYPE_p_std__mapT_std__string_ValueHolder_t attr) {
    Core_WrapperJNI.AdsTrackerCore_sendCustomAction__SWIG_1(swigCPtr, this, name, SWIGTYPE_p_std__mapT_std__string_ValueHolder_t.getCPtr(attr));
  }

  public boolean setTimestamp(double timestamp, String attributeName) {
    return Core_WrapperJNI.AdsTrackerCore_setTimestamp(swigCPtr, this, timestamp, attributeName);
  }

  public void sendAdBreakStart() {
    Core_WrapperJNI.AdsTrackerCore_sendAdBreakStart(swigCPtr, this);
  }

  public void sendAdBreakEnd() {
    Core_WrapperJNI.AdsTrackerCore_sendAdBreakEnd(swigCPtr, this);
  }

  public void sendAdQuartile() {
    Core_WrapperJNI.AdsTrackerCore_sendAdQuartile(swigCPtr, this);
  }

  public void sendAdClick() {
    Core_WrapperJNI.AdsTrackerCore_sendAdClick(swigCPtr, this);
  }

  public int getNumberOfAds() {
    return Core_WrapperJNI.AdsTrackerCore_getNumberOfAds(swigCPtr, this);
  }

}
