/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.newrelic.videoagent.jni.swig;

public interface Core_WrapperConstants {
  public final static double OBSERVATION_TIME = Core_WrapperJNI.OBSERVATION_TIME_get();
  public final static double HEARTBEAT_COUNT = Core_WrapperJNI.HEARTBEAT_COUNT_get();
}
