/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.newrelic.videoagent.jni.swig;

public class AttrList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AttrList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttrList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Core_WrapperJNI.delete_AttrList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AttrList() {
    this(Core_WrapperJNI.new_AttrList__SWIG_0(), true);
  }

  public AttrList(AttrList arg0) {
    this(Core_WrapperJNI.new_AttrList__SWIG_1(AttrList.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return Core_WrapperJNI.AttrList_size(swigCPtr, this);
  }

  public boolean empty() {
    return Core_WrapperJNI.AttrList_empty(swigCPtr, this);
  }

  public void clear() {
    Core_WrapperJNI.AttrList_clear(swigCPtr, this);
  }

  public ValueHolder get(String key) {
    return new ValueHolder(Core_WrapperJNI.AttrList_get(swigCPtr, this, key), false);
  }

  public void set(String key, ValueHolder x) {
    Core_WrapperJNI.AttrList_set(swigCPtr, this, key, ValueHolder.getCPtr(x), x);
  }

  public void del(String key) {
    Core_WrapperJNI.AttrList_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return Core_WrapperJNI.AttrList_has_key(swigCPtr, this, key);
  }

}
