/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.newrelic.videoagent.jni.swig;

public class TrackerCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TrackerCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TrackerCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Core_WrapperJNI.delete_TrackerCore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TrackerCore() {
    this(Core_WrapperJNI.new_TrackerCore(), true);
  }

  public CoreTrackerState state() {
    return CoreTrackerState.swigToEnum(Core_WrapperJNI.TrackerCore_state(swigCPtr, this));
  }

  public void updateAttribute(String name, ValueHolder value, String filter) {
    Core_WrapperJNI.TrackerCore_updateAttribute__SWIG_0(swigCPtr, this, name, ValueHolder.getCPtr(value), value, filter);
  }

  public void updateAttribute(String name, ValueHolder value) {
    Core_WrapperJNI.TrackerCore_updateAttribute__SWIG_1(swigCPtr, this, name, ValueHolder.getCPtr(value), value);
  }

  public void reset() {
    Core_WrapperJNI.TrackerCore_reset(swigCPtr, this);
  }

  public void setup() {
    Core_WrapperJNI.TrackerCore_setup(swigCPtr, this);
  }

  public String getViewId() {
    return Core_WrapperJNI.TrackerCore_getViewId(swigCPtr, this);
  }

  public int getNumberOfVideos() {
    return Core_WrapperJNI.TrackerCore_getNumberOfVideos(swigCPtr, this);
  }

  public String getCoreVersion() {
    return Core_WrapperJNI.TrackerCore_getCoreVersion(swigCPtr, this);
  }

  public String getViewSession() {
    return Core_WrapperJNI.TrackerCore_getViewSession(swigCPtr, this);
  }

  public int getNumberOfErrors() {
    return Core_WrapperJNI.TrackerCore_getNumberOfErrors(swigCPtr, this);
  }

  public void setLocked(boolean state) {
    Core_WrapperJNI.TrackerCore_setLocked(swigCPtr, this, state);
  }

  public boolean getLocked() {
    return Core_WrapperJNI.TrackerCore_getLocked(swigCPtr, this);
  }

  public void sendRequest() {
    Core_WrapperJNI.TrackerCore_sendRequest(swigCPtr, this);
  }

  public void sendStart() {
    Core_WrapperJNI.TrackerCore_sendStart(swigCPtr, this);
  }

  public void sendEnd() {
    Core_WrapperJNI.TrackerCore_sendEnd(swigCPtr, this);
  }

  public void sendPause() {
    Core_WrapperJNI.TrackerCore_sendPause(swigCPtr, this);
  }

  public void sendResume() {
    Core_WrapperJNI.TrackerCore_sendResume(swigCPtr, this);
  }

  public void sendSeekStart() {
    Core_WrapperJNI.TrackerCore_sendSeekStart(swigCPtr, this);
  }

  public void sendSeekEnd() {
    Core_WrapperJNI.TrackerCore_sendSeekEnd(swigCPtr, this);
  }

  public void sendBufferStart() {
    Core_WrapperJNI.TrackerCore_sendBufferStart(swigCPtr, this);
  }

  public void sendBufferEnd() {
    Core_WrapperJNI.TrackerCore_sendBufferEnd(swigCPtr, this);
  }

  public void sendHeartbeat() {
    Core_WrapperJNI.TrackerCore_sendHeartbeat(swigCPtr, this);
  }

  public void sendRenditionChange() {
    Core_WrapperJNI.TrackerCore_sendRenditionChange(swigCPtr, this);
  }

  public void sendError(String message) {
    Core_WrapperJNI.TrackerCore_sendError(swigCPtr, this, message);
  }

  public void sendDroppedFrame(int count, int elapsed) {
    Core_WrapperJNI.TrackerCore_sendDroppedFrame(swigCPtr, this, count, elapsed);
  }

  public void sendPlayerReady() {
    Core_WrapperJNI.TrackerCore_sendPlayerReady(swigCPtr, this);
  }

  public void sendDownload() {
    Core_WrapperJNI.TrackerCore_sendDownload(swigCPtr, this);
  }

  public void sendCustomAction(String name) {
    Core_WrapperJNI.TrackerCore_sendCustomAction__SWIG_0(swigCPtr, this, name);
  }

  public void sendCustomAction(String name, AttrList attr) {
    Core_WrapperJNI.TrackerCore_sendCustomAction__SWIG_1(swigCPtr, this, name, AttrList.getCPtr(attr), attr);
  }

  public void setOptions(AttrList opts) {
    Core_WrapperJNI.TrackerCore_setOptions__SWIG_0(swigCPtr, this, AttrList.getCPtr(opts), opts);
  }

  public void setOptions(AttrList opts, String action) {
    Core_WrapperJNI.TrackerCore_setOptions__SWIG_1(swigCPtr, this, AttrList.getCPtr(opts), opts, action);
  }

  public void startTimerEvent() {
    Core_WrapperJNI.TrackerCore_startTimerEvent(swigCPtr, this);
  }

  public void abortTimerEvent() {
    Core_WrapperJNI.TrackerCore_abortTimerEvent(swigCPtr, this);
  }

  public void trackerTimeEvent() {
    Core_WrapperJNI.TrackerCore_trackerTimeEvent(swigCPtr, this);
  }

  public boolean setTimestamp(double timestamp, String attributeName) {
    return Core_WrapperJNI.TrackerCore_setTimestamp(swigCPtr, this, timestamp, attributeName);
  }

}
