/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.newrelic.videoagent;

public class StupidTest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StupidTest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StupidTest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StupidTest_WrapperJNI.delete_StupidTest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void sayHello(String name) {
    StupidTest_WrapperJNI.StupidTest_sayHello(swigCPtr, this, name);
  }

  public String returnHello(String name) {
    return StupidTest_WrapperJNI.StupidTest_returnHello(swigCPtr, this, name);
  }

  public StupidTest() {
    this(StupidTest_WrapperJNI.new_StupidTest(), true);
  }

}
