/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.newrelic.videoagent;

public class StupidTest_WrapperJNI {
  public final static native void StupidTest_sayHello(long jarg1, StupidTest jarg1_, String jarg2);
  public final static native String StupidTest_returnHello(long jarg1, StupidTest jarg1_, String jarg2);
  public final static native long new_StupidTest();
  public final static native void delete_StupidTest(long jarg1);
}
